FORMAT: 1A
HOST: http://api.backfeed.cc/

# Backfeed

Polls is a simple API allowing consumers to view polls and vote in them.

## Agents [/agent]

### Get All Agents [GET]

+ Response 200 (application/json)

        [
            {
                id: "our unique id",
                name: "JohnLennon",
                handles: [
                        {
                            name: '@MyTwtterName',
                            type: 'twitter'
                        },
                        {
                            name: 'mrninja',
                            type: 'github'
                        }
                    ],
                collaborations: [
                        {
                            id: '546564',
                            tokens: 54,
                            reputation: 234
                        }
                    ],
                networks: [
                        {
                            id: 1,
                            name: 'Slant'
                        },
                        {
                            id: 2,
                            name: 'OuiShare'
                        }
                ]
            }
        ];

### Create Agent [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "name": "MyGoodName"
        }

+ Response 201 (application/json)


    + Body

            {
                "id": "14375107-826d-4f26-a859-350bee9df587"
            }
