FORMAT: 1A
HOST: {{baseURL}}

# Backfeed API
General purpose API

# Group Handle

## Handle [/handle{?handleType,handleName}]

### Delete all Handles [DELETE]

### Create Handle [POST]
+ Parameters
    + handleType (string, required)

    + handleName (string, required)



## Handle 1 [/handle/1]

### Delete Specific Handle [DELETE]

### Get Specific Handle [GET]


## Handle [/handle]

### Get All Handles [GET]



# Group Contribution

## Contribution [/contribution{?collaborationId,agentId,type,comment}]

### Create a Milestone [POST]
+ Parameters
    + collaborationId (number, required)

    + agentId (number, required)

    + type (string, required)

    + comment (string, required)


+ Request (application/json)
    + Attributes (Create a MilestoneRequest)


## Contribution [/contribution{?collaborationId,agentId,type,comment}]

### Create Contribution [POST]
+ Parameters
    + collaborationId (number, required)

    + agentId (number, required)

    + type (string, required)

    + comment (string, required)


+ Request (application/json)
    + Attributes (Create ContributionRequest)


## Contribution [/contribution{?collaborationId}]

### Get All Contributions [GET]

### Get Contributions by Collaboration [GET]
+ Parameters
    + collaborationId (number, required)



## Contribution [/contribution{?key,contains}]

### Get Contributions by Title [GET]
+ Parameters
    + key (string, required)

    + contains (string, required)



## Contribution 1 [/contribution/1]

### Get Specific Contribution [GET]



# Group Network

## Network [/network{?description,name,creator,protocol,agents,collaborations}]

### Create Network [POST]
+ Parameters
    + description (string, required)

    + name (string, required)

    + creator (number, required)

    + protocol (string, required)

    + agents (string, required)

    + collaborations (string, required)



## Network [/network]

### Get All Networks [GET]


## Network 1 [/network/1]

### Get Specific Network [GET]



# Group Agent

## Agent UpdateHandle 1 [/agent/updateHandle/1{?handleType,handleName}]

### Update Agent Handle [PUT]
+ Parameters
    + handleType (string, required)

    + handleName (string, required)



## Agent 1 [/agent/1]

### Get Specific Agent [GET]


## Agent UpdateNetwork 1 [/agent/updateNetwork/1{?networkId}]

### Update Agent Network [PUT]
+ Parameters
    + networkId (number, required)



## Agent FindByHandle [/agent/findByHandle{?handleType,handleName}]

### Get Agent by Handle [GET]
+ Parameters
    + handleType (string, required)

    + handleName (string, required)



## Agent AllByNetwork [/agent/allByNetwork{?networkId}]

### Get All Agents in Network [GET]
+ Parameters
    + networkId (number, required)



## Agent AllInCollaboration [/agent/allInCollaboration{?collaborationId}]

### Get All Agents in Collaboration [GET]
+ Parameters
    + collaborationId (number, required)




# Group Evaluation

## Evaluation 1 [/evaluation/1]

### Get Specific Evaluation [GET]


## Evaluation [/evaluation{?agentId,tokens,contributionId,stake}]

### Create Evaluation [POST]
+ Parameters
    + agentId (number, required)

    + tokens (number, required)

    + contributionId (number, required)

    + stake (number, required)



## Evaluation [/evaluation{?contributionId}]

### Get All Evaluations for a Contribution [GET]
+ Parameters
    + contributionId (number, required)




# Group Collaboration

## Collaboration [/collaboration{?agentId,networkId}]

### Get All Collaborations By Agent in Network [GET]
+ Parameters
    + agentId (number, required)

    + networkId (number, required)



## Collaboration [/collaboration{?name,creator,description,tokenName,tokenSymbol,tokenTotal,protocol,networkId,handles,contributors,comment}]

### Create Collaboration [POST]
+ Parameters
    + name (string, required)

    + creator (number, required)

    + description (string, required)

    + tokenName (string, required)

    + tokenSymbol (string, required)

    + tokenTotal (number, required)

    + protocol (string, required)

    + networkId (number, required)

    + handles (string, required)

    + contributors (string, required)

    + comment (string, required)



## Collaboration [/collaboration{?networkId}]

### Get All Collaborations for Network [GET]
+ Parameters
    + networkId (number, required)



## Collaboration 1 [/collaboration/1]

### Get Specific Collaboration [GET]


## Collaboration [/collaboration]

### Get All Collaborations [GET]



# Agent [/agent{?name}]

## Get All Agents [GET]

## Create Agent [POST]
+ Parameters
    + name (string, required)



# Contribution [/contribution{?key,contains}]

## Get Contributions By Description query [GET]
+ Parameters
    + key (string, required)

    + contains (string, required)



# Agent 1 [/agent/1{?handleType,handleName}]

## Register a Handle for Agent [POST]
+ Parameters
    + handleType (string, required)

    + handleName (string, required)



# Agent [/agent{?name,handleType,handleName}]

## Create Agent Handle [POST]
+ Parameters
    + name (string, required)

    + handleType (string, required)

    + handleName (string, required)



# Data Structures

## Create a MilestoneRequest (object)


### Properties
+ `content` (Content, required) 


## Content (object)


### Properties
+ `title` (string, required) 
+ `description` (string, required) 
+ `milestoneOrigin` (number, required) 
+ `milestoneContributions` (array[number], required) 


## Create ContributionRequest (object)


### Properties
+ `content` (Content3, required) 


## Content3 (object)


### Properties
+ `title` (string, required) 
+ `description` (string, required) 
+ `links` (array[string], required) 

